server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

#数据库配置
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/db_webcast?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

     #REDIS
    redis:
        host: 127.0.0.1
        port: 6379
        #database: 2
        password:
        timeout: 2000
        default:
          expire-seconds: 3600
        pool:
          # 连接池中的最大空闲连接
          max-idle: 8
          min-idle: 2
          max-active: 16
          max-wait: 1000
          testOnBorrow: true


mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.taofeng.webcast.dao.mapper

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
